### ISSUE TITLE
Crash - [UXInternalLog log]

### ISSUE THREAD

**Issue by andresRZem** [uxcam/uxcam-ios-sdk#11]
Hi there, our app is crashing on startup due to `Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]` affecting many users daily

```Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  CoreFoundation                 0x15e6c -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
3  CoreFoundation                 0x15a88 +[NSDictionary dictionaryWithObjects:forKeys:count:]
4  <myApp>                     0x144c2a4 -[UXInternalLog log]
5  <myApp>                     0x144c410 -[UXInternalLog logData]
6  <myApp>                      0x144e8f4 __31-[UXInternalLogger logMessage:]_block_invoke
7  libdispatch.dylib              0x3dd4 _dispatch_client_callout
8  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete
9  <myApp>                      0x144e8a4 -[UXInternalLogger logMessage:]
10 <myApp>                     0x1419d80 +[UXCamHandler addInternalTag:logLevel:properties:]
11 <myApp>                      0x13fe5c0 +[UXCam initialize]
12 libobjc.A.dylib                0x1014c CALLING_SOME_+initialize_METHOD
13 libobjc.A.dylib                0xd468 initializeNonMetaClass
14 libobjc.A.dylib                0xd0fc initializeAndMaybeRelock(objc_class*, objc_object*, locker_mixin<lockdebug::lock_mixin<objc_lock_base_t> >&, bool)
15 libobjc.A.dylib                0x5170 lookUpImpOrForward
16 libobjc.A.dylib                0x34c4 _objc_msgSend_uncached(AppCoordinator+BaseConfiguration.swift:242)
19 <myApp>                      0x3b946c specialized SceneDelegate.scene(_:willConnectTo:options:) + 36 (SceneDelegate.swift:36)
20 <myApp>                      0x3b8390 @objc SceneDelegate.scene(_:willConnectTo:options:) (<compiler-generated>)
21 ???                            0x193f38cc0 (Missing)
22 ???                            0x1941e0d28 (Missing)
23 ???                            0x19409d94c (Missing)
24 ???                            0x19409d600 (Missing)
25 FrontBoardServices             0x1a974 -[FBSScene _callOutQueue_didCreateWithTransitionContext:completion:]
26 FrontBoardServices             0x1a808 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke.108
27 FrontBoardServices             0x166cc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
28 FrontBoardServices             0x1acc4 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke
29 libdispatch.dylib              0x3dd4 _dispatch_client_callout
30 libdispatch.dylib              0x786c _dispatch_block_invoke_direct
31 FrontBoardServices             0x17d58 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
32 FrontBoardServices             0x17cd8 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible]
33 FrontBoardServices             0x17bb0 -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource]
34 CoreFoundation                 0x56834 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
35 CoreFoundation                 0x567c8 __CFRunLoopDoSource0
36 CoreFoundation                 0x542f8 __CFRunLoopDoSources0
37 CoreFoundation                 0x53484 __CFRunLoopRun
38 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific
39 GraphicsServices               0x11a8 GSEventRunModal
40 ???                            0x1941a890c (Missing)
41 ???                            0x19425c9d0 (Missing)
42 ???                            0x1943d6384 (Missing)
43 <myApp>                      0x46f64 main (AppDelegate.swift)
44 ???                            0x1b5221e4c (Missing)
```

We are using UXCam 3.6.15

Thank you in advance for your support.

**Comment by gabrieluxcam** [comment]
Hello @andresRZem thank you for raising this. 

Would it be possible to share a sample or snippet of how you're setting up the SDK? 
Also, does this happen on every run or is it somewhat randomised? 


Our developers will work on this with high priority and we will let you know asap. 

Thanks

**Comment by andresRZem** [comment]
Hi @gabrieluxcam 

This is a random crash, we haven't been able to replicate it, but we have several reports from Crashlytics

we are running this code from the SceneDelegate `willConnectTo session` method

```swift
let configuration = UXCamConfiguration(appKey: "apiKey")
UXCam.optIntoSchematicRecordings()
UXCam.start(with: configuration)
```

**Comment by gabrieluxcam** [comment]
Hello @andresRZem  thank you for your patience. 
We're already making progress here and as soon as the fix is done and tested we'll notify you, again apologies for all the hassle. Thanks!

**Comment by andresRZem** [comment]
Hi @gabrieluxcam that's great, thank you

**Comment by gabrieluxcam** [comment]
Hello @andresRZem  thanks for your patience. This is now fixed in SDK update 3.6.16, just published today, it would be extremely helpful if you can give it a go and let us know if anything. 

Thanks!

**Comment by andresRZem** [comment]
Hi @gabrieluxcam thank you so much, let me try and I'll let you know

**Comment by andresRZem** [comment]
Hi @gabrieluxcam We released a new version of our app, and we haven't seen any more crashes, you can mark this issue as resolved. Thank you so much

**Comment by gabrieluxcam** [comment]
Wonderful news @andresRZem happy to hear that. Please don't hesitate to reach out if anything. Closing this topic then. Thanks!

**Comment by hassanilyas786** [comment]
Hi,
Same crash in 3.6.25. 

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

 Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x11a21c __exceptionPreprocess
1  libobjc.A.dylib                0x31abc objc_exception_throw
2  CoreFoundation                 0x108bd8 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
3  CoreFoundation                 0x2aca0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
4  UpTicker                       0xbd3b94 +[UXCamPLCrashReportFormatter valueForCrashReport:withCustomData:fullCrashReport:]
5  UpTicker                       0xbd36b8 +[UXCamPLCrashReportFormatter anrDataFromCrashReport:tos:]
6  UpTicker                       0xb81dcc -[UXCam_KSCrashDeadlockMonitor handleDeadlock]
7  UpTicker                       0xb821b4 -[UXCam_KSCrashDeadlockMonitor runMonitor]
8  Foundation                     0x75804 __NSThread__start__
9  libsystem_pthread.dylib        0x3344 _pthread_start
10 libsystem_pthread.dylib        0xab8 thread_start
