### ISSUE TITLE
upload-dlsym.sh not properly signed

### ISSUE THREAD

**Issue by davidichung** [uxcam/uxcam-ios-sdk#15]
I'm seeing this error when I attempt to build a distribution version of my app with the sdk.

"Invalid Signature. Code object is not signed at all. The file at path \U201cWGU.app/Frameworks/UXCam.framework/uxcam-upload-dsym.sh\U201d is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose \U201cClean All\U201d in Xcode, delete the \U201cbuild\U201d directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: 008f2b74-3752-41f6-9f8f-12486cd91d4f)";

**Comment by gabrieluxcam** [comment]
Hello @davidichung thanks for flagging this. 

Indeed we've identified this recently, this is related to the script that we added for automatic upload of dsym files in our latest release. We have replicated this issue and this only occurs for `spm` and should work fine for `cocoapods`. We are trying to fix this and will probably release a new version by tomorrow or the day after with the fix.

Apologies for the hassle. 

This should not be happening for 3.6.17 however, could you confirm? Thanks

**Comment by davidichung** [comment]
yes, I can confirm it is happening on 3.6.17. We are using Swift Package Manager.

<img width="1567" alt="Screenshot 2024-11-21 at 8 47 50 AM" src="https://github.com/user-attachments/assets/6f7a9fd7-3d74-4bba-a67a-e15b470c17b0">
<img width="1623" alt="Screenshot 2024-11-21 at 8 47 15 AM" src="https://github.com/user-attachments/assets/6587d916-e791-4660-b0a6-d76dbc543dbb">

**Comment by gabrieluxcam** [comment]
Thank you @davidichung  I will confirm this asap with our team.

**Comment by felixinkinto** [comment]
Hi, our team is experiencing the same issue as well. 
For us, it started occurring after we updated to UXCam version 3.6.18. 
With version 3.6.17, we didn’t encounter any problems during archiving.

**Comment by gabrieluxcam** [comment]
Hello @cagysek @felixinkinto if you first upgraded to 3.6.18 and it has cache that it gets copied,which is not cleared when you switched back to 3.6.17. you need to first remove UXCam completely, and then readd 3.6.17. It should not occur afterwards.

However we are close to shipping the fix and could very well be today. I will update this thread. Thanks for your patience.

**Comment by cagysek** [comment]
@gabrieluxcam We haven't upgraded to  version 3.6.18. We have been using version 3.6.17 for about a month. Approximately two days ago the release stopped working with error above

**Comment by gabrieluxcam** [comment]
@cagysek @davidichung @felixinkinto We have released now the patched 3.6.19 version containing this fix, it would be extremely helpful to give it a try and le us know if all works as expected now. 

We will also be sharing in our documentation the steps for making use of the new crash symbolication feature.

**Comment by cagysek** [comment]
@gabrieluxcam I tried release to app store connect and it passed. Thank you guys for your speedy fix ❤️

**Comment by davidichung** [comment]
Confirmed Fixed. @cagysek Thank you!
