### ISSUE TITLE
Tutorial links to old sdk

### ISSUE THREAD

**Issue by joeldrotleff** [uxcam/uxcam-ios-sdk#3]
Following the tutorial here: https://developer.uxcam.com/docs/ios.

It shows in the image the url to the old repo (https://github.com/uxcam/ios-sdk)

**Comment by Egor-UXCam** [comment]
Hello @joeldrotleff! 

Thanks a lot for the heads-up, we will update the doc soon.

**Comment by gabrieluxcam** [comment]
Thank you @joeldrotleff it has been updated now.
