### ISSUE TITLE
Cannot Validate archive in Xcode 15.3

### ISSUE THREAD

**Issue by andy-vanwagoner-jn** [uxcam/uxcam-ios-sdk#6]
After archiving an app that uses the UXCamSwiftUI package with Xcode 15.3, validation fails due to signature errors with UXCam libraries. Is there a known workaround?

<img width="741" alt="Screenshot 2024-03-08 at 9 41 59 AM" src="https://github.com/uxcam/uxcam-ios-sdk/assets/82965077/8092ec23-ad89-45da-9e31-56900d4f0fd9">

**Comment by rokgregoric** [comment]
Same here:
<img width="684" alt="Screenshot 2024-03-09 at 5 25 07 AM" src="https://github.com/uxcam/uxcam-ios-sdk/assets/168918/576111c9-f6cc-4ceb-bd77-aaf93a422b39">

**Comment by gabrieluxcam** [comment]
Hello @andy-vanwagoner-jn @rokgregoric thanks for bringing this up, we're checking this with our developers and will provide an update asap.

**Comment by IhorShevchuk** [comment]
I have the same issue. Please remove shell scripts and other not needed files from framework.

**Comment by gabrieluxcam** [comment]
Hello @IhorShevchuk @andy-vanwagoner-jn @rokgregoric we have released a fix for this in our new SDK update version 3.6.11, it contains critical fixes aside from this one so it is highly suggested to upgrade asap. 

Once again, thank you for your collaboration and patience. 

I will mark this as closed but feel free to reach out if anything.

**Comment by IhorShevchuk** [comment]
Works for me! Thanks for quick fix.

**Comment by rokgregoric** [comment]
Works for me as well. Thanks 🙏
