### ISSUE TITLE
Infinite cycle on [UXControllerUtility findVisibleControllerForHostingController:] in native MoreNavigationController

### ISSUE THREAD

**Issue by lehenealexandra** [uxcam/uxcam-ios-sdk#9]
We just discovered an infinite cycle in app after upgrading to latest UxCam version 3.6.11 on method "findVisibleControllerForHostingController" 

We have a UITabarControlller in app set as root with multiple tabs, so then we also have the native generated MoreNavigationController https://developer.apple.com/documentation/uikit/uitabbarcontroller/1621183-morenavigationcontroller and when reaching any item from the list shown in MoreNavigationController and scrolling up/down to see the bouncing on the list we have this crash, application is completely frozen  without possibility to click anything. 

As I tested this crash is not happening in version '3.5.1' of 'UXCam', only in 3.6.11.

[UXCamCrash.txt](https://github.com/uxcam/uxcam-ios-sdk/files/15007023/UXCamCrash.txt)

**Comment by gabrieluxcam** [comment]
Hello @lehenealexandra  thanks for reaching out. 

Indeed we will require to look into this potential issue, I have already passed it along to our developers and any updates or follow up details necessary we'll reach out if needed. 

Thanks again for your collaboration and patience on this matter.

**Comment by gabrieluxcam** [comment]
Hello @lehenealexandra thanks for your patience on this matter, we've just released an upgraded SDK version 3.6.12 of the iOS SDK containing this fix. 

Please feel free to give it a try and let us know if anything. 

Again, thanks for your patience and collaboration.

**Comment by lehenealexandra** [comment]
Yes, I don't see the crash anymore in latest version. Thanks a lot! 😊
